apiVersion: v1
kind: Service
metadata:
  name: lkmbot-service-lb
  namespace: lkmbot-ns
  labels:
    app: lkmbot-stack
spec:
  type: LoadBalancer
  selector:
    app: lkmbot-stack
  ports:
    - name: napcat-web
      port: 6099
      targetPort: 6099
    - name: lkmbot-web
      port: 6185
      targetPort: 6185