apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lkmbot-data-pvc
  namespace: lkmbot-standalone-ns
  labels:
    app: lkmbot-standalone
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: standard # uncomment and set proper StorageClass